name: "CI"

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://releases.nixos.org/nix/nix-2.28.1/install
          extra_nix_config: |
            accept-flake-config = true

      - name: Perform flake check
        run: nix flake check --all-systems

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://releases.nixos.org/nix/nix-2.28.1/install
          extra_nix_config: |
            accept-flake-config = true

      - name: Perform colmena build
        run: nix run .#build

  ci_pass:
    if: always()
    needs:
      - lint
      - build
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the required jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
