name: Create Install ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build Installer ISO
        run: nix build .#installer-iso

      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.1'

      - name: Generate Tailscale auth-key
        env:
          TS_API_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TS_API_CLIENT_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
        run: go run tailscale.com/cmd/get-authkey@latest -tags tag:ci -reusable -preauth=false > tailscale_key

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release="$(date -u +%F)-${GITHUB_SHA:0:7}"
          gh release create "$release" \
            --generate-notes \
            result/iso/wind-tunnel-runner-auto-installer.iso \
            tailscale_key
